services:
  nginx:
    image: nginx:alpine
    container_name: api-gateway-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth_dev
      - user_dev
      - post_dev
    networks:
      - connect

  connect_redis:
    image: redis:8-alpine
    container_name: connect_redis
    ports:
      - "6379:6379"
    volumes:
      - connect_redis_data:/data
    networks:
      - connect

  connect_postgres:
    image: postgres:18-alpine
    container_name: connect_postgres
    env_file:
      - ./common-env/.env
    volumes:
      - connect_postgres_data:/var/lib/postgresql/data
    networks:
      - connect

  auth_dev:
    profiles:
      - dev
    build:
      context: ./auth-service
      dockerfile: Dockerfile
      target: dev
    container_name: auth_dev
    image: auth_dev_image
    env_file:
      - ./auth-service/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    volumes:
      - ./auth-service:/app
      - auth_node_modules:/app/node_modules
    networks:
      - connect
    depends_on:
      - connect_redis

  auth_prod:
    profiles:
      - production
    build:
      context: ./auth-service
      dockerfile: Dockerfile
      target: production
    container_name: auth_prod
    image: auth_prod_image
    env_file:
      - ./auth-service/.env
    networks:
      - connect
    depends_on:
      - connect_redis

  user_dev:
    profiles:
      - dev
    build:
      context: ./user-service
      dockerfile: Dockerfile
      target: dev
    container_name: user_dev
    image: user_dev_image
    env_file:
      - ./user-service/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    volumes:
      - ./user-service:/app
      - user_node_modules:/app/node_modules
    networks:
      - connect
    dns:
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  
    depends_on:
      - connect_redis
      - connect_postgres

  user_prod:
    profiles:
      - production
    build:
      context: ./user-service
      dockerfile: Dockerfile
      target: production
    container_name: user_prod
    image: user_prod_image
    env_file:
      - ./user-service/.env
    networks:
      - connect
    depends_on:
      - connect_redis
      - connect_postgres

  post_dev:
    profiles:
      - dev
    build:
      context: ./post-service
      dockerfile: Dockerfile
      target: dev
    container_name: post_dev
    image: post_dev_image
    env_file:
      - ./post-service/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    volumes:
      - ./post-service:/app
      - post_node_modules:/app/node_modules
    networks:
      - connect
    depends_on:
      - connect_redis
      - connect_postgres

  post_prod:
    profiles:
      - production
    build:
      context: ./post-service
      dockerfile: Dockerfile
      target: production
    container_name: post_prod
    image: post_prod_image
    env_file:
      - ./user-service/.env
    networks:
      - connect
    depends_on:
      - connect_redis
      - connect_postgres

networks:
  connect:


volumes:
  connect_redis_data:
  connect_postgres_data:
  auth_node_modules:
  user_node_modules:
  post_node_modules:
